ccnmtl/worth2

media/css/ssnm.css
media/js/src/ssnm/components/modal-dialog.js
media/js/src/ssnm/controllers/supporter.js
media/js/src/ssnm/controllers/supporters.js
media/js/src/ssnm/models/supporter.js
media/js/src/ssnm/routes/application.js
media/js/src/ssnm/views/modal.js
worth2/main/models.py
worth2/settings_shared.py
worth2/ssnm/apiviews.py
worth2/ssnm/auth.py
worth2/ssnm/migrations/0002_auto_20150114_1431.py
worth2/ssnm/models.py
worth2/ssnm/serializers.py
worth2/ssnm/tests/test_apiviews.py
worth2/templates/ssnm/ssnm.html
worth2/urls.py

Participants' supporters now get loaded with ember-data and put in the
appropriate box in the support map.
I'm glad I found the rest_framework_ember package - it automatically
does all the tedious json format stuff that I did manually for Weather
Roulette.
The big thing left to implement is adding/editing supporters.

Social Support Network Map v2

---

requirements.txt

While setting up Marc's sandbox on kodos, there were problems
bootstrapping with a github URL in requirements.txt. Using a normal pip
package works, though.

Use pagetree 1.0.3

---

media/js/src/ssnm/components/modal-dialog.js
media/js/src/ssnm/components/supporter-box.js
media/js/src/ssnm/controllers/edit-supporter.js
media/js/src/ssnm/controllers/supporter.js
media/js/src/ssnm/controllers/supporters.js
media/js/src/ssnm/routes/application.js
worth2/templates/ssnm/ssnm.html

- Participants can now edit supporters by clicking on them
- Bugfix where supporter boxes were showing before being saved

Add supporter editing in SSNM activity - PMT #98027

---

worth2/main/mixins.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/urls.py

Fix redirect loop that occurs when a participant navigates to `/`.
- Removed ActiveUserRequiredMixin - it was just confusing things. For
now, all auth is handled in urls.py. If it turns out that using mixins
is more standard, I can switch everything over to that, but I
shouldn't be using both mixins and urls.py for auth.
- Add participant with no avatar test

Fix redirect loop

---

requirements.txt
worth2/main/admin.py
worth2/main/migrations/0005_protectivebehaviorresults.py
worth2/main/models.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/settings_shared.py
worth2/templates/main/protective_behavior_results.html
worth2/templates/pagetree/page.html
worth2/urls.py

I wasn't able to get django's form validation integrated with pagetree,
I just added some custom validation to quizblock's Submission object.
Submissions are created immediately when a Quiz is submitted, even if it
has no data in it. My workaround is to override PageView.get, and delete
any Submission that doesn't have a Response associated with it.
Going forward, one thing I want to do is make pagetree.PageView's 'get'
method easier to override so this copied code will become unnecessary.
I've also added a model for aggregating these quiz results.
A few of my quiz test assertions are commented out with `FIXME` notes since they're not passing yet, for some reason.

Add submission empty validation for Protective Behaviors - PMT #98028

---

worth2/main/admin.py
worth2/main/migrations/0006_auto_20150206_1402.py
worth2/main/models.py
worth2/main/templatetags/quizsummary.py
worth2/main/views.py
worth2/settings_shared.py
worth2/templates/main/protective_behavior_results.html
worth2/templates/pagetree/page.html

This adds a 'stuff i do' custom pageblock to be used in the
protective behavior quiz, similar to the QuizSummaryBlock in
meaningfulconsent:
https://github.com/ccnmtl/meaningfulconsent/blob/master/meaningfulconsent/main/models.py#L139

Protective behavior results

---

worth2/goals/admin.py
worth2/goals/migrations/0001_initial.py
worth2/goals/models.py
worth2/goals/tests/test_views.py
worth2/settings_shared.py
worth2/templates/base.html
worth2/templates/goals/goal_setting_block.html
worth2/templates/goals/goal_setting_block_formset.html
worth2/templates/pagetree/page.html

This is a work-in-progress version of the goal setting activity - POST functionality isn't built yet.
I chose not to use quizblock for this because it seemed from the requirements to be easier to make a custom pageblock.
Some things that will take some figuring out are:
* Separating the GoalSlots into different gates views .. right now all three are rendering in `goal_settings_block.html`.
* Input validation

 Goal setting activity work-in-progress. PMT #98022

---

worth2/goals/forms.py
worth2/goals/migrations/0009_auto_20150216_1411.py
worth2/goals/migrations/0010_auto_20150216_1659.py
worth2/goals/mixins.py
worth2/goals/models.py
worth2/goals/tests/factories.py
worth2/goals/tests/test_models.py
worth2/goals/tests/test_views.py
worth2/main/tests/helpers.py
worth2/main/views.py
worth2/templates/goals/goal_check_in_block.html
worth2/templates/goals/goal_review_block.html
worth2/templates/goals/goal_setting_block.html

This adds the goal check-in activity:
This also includes a refactor of my PageView form customizations -- separating a lot of that logic out to `/worth2/goals/mixins.py`. There's also tests for the check-in activity and all the goal-related factories now.

Goal checkin - PMT #98023

---

worth2/goals/tests/test_views.py

I got around gating in the tests with the 'unlock_hierarchy' test
helper, not the section ordering.

Remove inaccurate comment

---

media/css/main.css
media/js/src/app.js
media/js/src/views/manage-participant-filter.js
media/js/src/views/sign-in-participant-filter.js
worth2/main/forms.py
worth2/main/models.py
worth2/main/tests/test_models.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/templates/main/facilitator_sign_in_participant.html
worth2/templates/main/participant_edit_row.html
worth2/templates/main/participant_list.html

Adds dropdown boxes on participant manage and sign-in views. "All Cohorts" and "Unassigned" are always shown as options.
Manage participants page:
Participant sign-in page:

Filter participants by cohort - PMT #98031

---

worth2/templates/main/avatar_selector_block.html

For some reason, pagetree isn't creating its page-wide `<form>`
for the avatar selector block. I have needs_submit set to true
for this custom pageblock.
I've seen this happen in other places of worth as well - the goal
forms needed my own `<form>` tag in the template.

Fix avatar selector form submission - PMT #99521

---

worth2/ssnm/apiviews.py
worth2/ssnm/auth.py
worth2/ssnm/migrations/0004_auto_20150218_0927.py
worth2/ssnm/models.py
worth2/ssnm/tests/factories.py
worth2/ssnm/tests/test_apiviews.py

I'm moving the relation on Supporter from Participant to a normal
django User, so all authenticated users can use the SSNM activity.

Attach SSNM's Supporter to User instead of Participant - PMT #98027

---

worth2/main/forms.py
worth2/main/tests/factories.py
worth2/main/tests/test_views.py
worth2/templates/main/facilitator_sign_in_participant.html

This was solved by iterating over the form's "choices" instead of its
"queryset". "choices" is what django expects you to iterate over.
I was iterating over "queryset" as a sort of workaround, because I
need to populate the dropdown with the study ID as well as the cohort ID,
and I didn't know how to get ModelChoiceField to give me the whole object.
I added the RawModelChoiceField as a ModelChoiceField that gives the
whole instance to the template, instead of a single field.
The test for this is not quite complete since I ran into a problem where
I can't see the participant ID dropdown in the test.

Fix stale cohort ID bug - PMT #99554

---

worth2/templates/main/facilitator_sign_in_participant.html

I wasn't displaying this form field's errors correctly. It looks better now:

Fix error display on sign-in form. PMT #99556

---

media/css/main.css
worth2/templates/quizblock/single_choice.html
worth2/templates/quizblock/single_choice_show_answer.html

We need to address this issue:
https://github.com/ccnmtl/django-quizblock/issues/35
so we don't have to deal with these problems!

Protective Behaviors quiz style fixes - plain quiz conflicts

---

media/css/main.css

I'm using a flexible width for this instead of a fixed width, which should
work for both the plain quizzes and the protective behaviors rate-my-risk
quiz.

Likert style changes to better match wireframe

---

worth2/protectivebehaviors/templatetags/quizsummary.py
worth2/protectivebehaviors/tests/test_templatetags.py
worth2/templates/protectivebehaviors/whats_your_level_feedback.html
worth2/templates/quizblock/question.html

In the process, I refactored the get_quiz_summary templatetag. I
simplified it a lot by using the @register.assignment_tag decorator.

Add customized feedback for the ratemyrisk quiz - PMT #98028

---

media/js/src/views/unlocker.js
requirements.txt
worth2/goals/migrations/0015_auto_20150227_1212.py
worth2/goals/migrations/0016_auto_20150227_1224.py
worth2/goals/models.py
worth2/main/generic/models.py
worth2/main/models.py
worth2/main/views.py
worth2/protectivebehaviors/models.py
worth2/ssnm/models.py
worth2/templates/main/avatar_selector_block.html
worth2/templates/pagetree/page.html

This adds pageblock gating for goal setting/checkin blocks and avatar selector block. There's also a lot of cleanup in this commit.
One outstanding issue here is my goal setting and checkin pages are rendering incorrectly when `unlocked` is `False`. However, when I click the 'submit' button without entering any data, the validation error appears as normal, and everything looks correct. Have you run into this problem before / know how to fix it?

Add gating for locked pageblocks - PMT #99684

---

media/css/video.css
worth2/templates/main/video_block.html

This makes the youtube videos fill the whole width of the page.
http://getbootstrap.com/components/#responsive-embed

Add responsive video embed from Marc - PMT #99807

---

media/js/src/app.js
media/js/src/main.js
worth2/templates/base.html

I'm not using bootstrap's JS anywhere in worth's JS app,
and taking bootstrap out of require.js noticeably speeds up
js loading.

Prevent bootstrap from loading in the require.js app

---

media/js/src/forms/selftalk-internalstatementform.js
worth2/selftalk/forms.py
worth2/selftalk/mixins.py
worth2/selftalk/tests/test_views.py

This cleans up the selftalk tests to make it clear whether it's testing
and 'internal' or 'external' scenario. Also includes some changes to the
internal negative statement setting form, which will be implemented once
the spec for this form solidifies (PMT #98029).

Differentiate internal/external selftalk in tests - PMT #98029

---

worth2/main/models.py
worth2/templates/main/avatar_selector_block.html

Instead of displaying a non-functional form when the avatar is selected,
make it clear that one is already chosen.

Show a different view if the avatar selector has been submitted

---

worth2/goals/admin.py
worth2/goals/migrations/0017_auto_20150312_0940.py
worth2/goals/mixins.py
worth2/goals/models.py
worth2/goals/tests/factories.py
worth2/goals/tests/test_views.py
worth2/templates/goals/goal_check_in_block.html
worth2/templates/goals/goal_setting_block.html

The spec for these goal options changed slightly. Each goal type has
the same set of goal options, so the goal options should be associated
with goal type instead of the specific goal-setting pageblock.
Also:
* Get rid of extra submit button in goal setting/checkin blocks

Associate goal options with goal type instead of pageblock - PMT #98022

---

media/js/src/views/goal-checkin-form.js
media/js/src/views/goal-setting-form.js
worth2/goals/admin.py
worth2/goals/models.py
worth2/templates/goals/goal_check_in_block.html
worth2/templates/goals/goal_setting_block.html

Pagetree's auto-generated `<form>` tag has a few problems preventing
me from using it with the goal forms:
* After submitting an invalid form, Pagetree's Submit button disappears,
preventing the user from being able to submit the form again.
* The "change my answers" form isn't compatible with formsets. See
https://github.com/ccnmtl/django-pagetree/issues/58
My solution is to again have the pageblock render its own `<form>`. This
necessitates an unfortunate hack: hiding pagetree's Submit button with
JavaScript. This is one of the reasons I think needs_submit should be
broken out into two different configurable params: Something like
`handles_post_data` and `renders_form`. Related to issue here:
https://github.com/ccnmtl/django-pagetree/issues/44

Fix form issues on goal forms

---

worth2/settings_production.py
worth2/settings_staging.py

I'd like to make sure we have CORS headers working properly on
S3, and then switch to cloudfront once we figure it out.

Revert to S3 for now instead of cloudfront

---

worth2/main/views.py
worth2/selftalk/models.py
worth2/templates/pagetree/page.html
worth2/templates/selftalk/statement_block.html

I fixed the issues by setting all the influential context variables
in PageView's get_context_data().

Fix some problems with inconsistent form behavior on selftalk forms

---

worth2/settings_production.py
worth2/settings_staging.py

Now that I've got the CORS issue with my three.js scene sorted
out on S3, I'll try using cloudfront again. The worth2 cloudfront
distributions are already set up to forward the necessary headers.

Try cloudfront again

---

worth2/goals/models.py
worth2/main/generic/models.py
worth2/main/tests/test_models.py
worth2/main/tests/test_utils.py
worth2/main/tests/test_views.py
worth2/main/utils.py
worth2/main/views.py
worth2/selftalk/models.py

I'm now referring to these as "modules" internally, while still
displaying this as "Session" in the UI.
This should fix the session display problem on the participant sign-in
page.

Fix session/module numbers - PMT #100689

---

media/js/src/ssnm/controllers/supporters.js
media/js/src/ssnm/views/modal.js
worth2/templates/ssnm/ssnm_js.html
worth2/templates/ssnm/ssnm_page_block.html

This adds a new "Too many people" dialog when you try to
add more than 5 supporters to your network map.
Also, I've added some key event behavior in the add/edit supporter
modals:
- When 'Escape' is pressed, the window closes.
- When 'Enter' is pressed, nothing happens.

SSNM changes - PMT #100721, #100722

---

worth2/main/models.py
worth2/main/tests/test_models.py
worth2/templates/main/facilitator_sign_in_participant.html

This fixes the bug where the module displayed in "The next, new session"
on the sign-in page is inaccurate.
This also fixes a bug with Participant.highest_module_accessed(),
which wasn't looking at all the children of modules, only the modules
themselves.

Add Participant.next_module() - PMT #100689

---

worth2/templates/main/avatar_selector_block.html

At issue: The avatar block page was painting without a form, rendering the submit buttons useless.  
Explanation: By default, pagetree renders a form only if "needs_submit" is True and "is_submitted (pageblock.unlocked)" is False. (https://github.com/ccnmtl/worth2/blob/master/worth2/templates/pagetree/page.html#L52) The Avatar block wants to make submit optional, so returns True for needs_submit and is_unlocked. (https://github.com/ccnmtl/worth2/blob/master/worth2/main/models.py#L93)
Short-term resolution: Render the form inside the Avatar block template. This is fine as long as the Avatar Block is the only block on the page.
Longer-term: Ideally, the user would be forced to submit something, e.g. "No Thanks!", allowing a more consistent "unlocked" flow. Let's review the requirements for …

Fix Avatar Block form submit

---

worth2/goals/mixins.py

For Goal Setting & Goal Check In: mark the user's page visit as "complete" once a valid response is submitted.

Complete page visits

---

worth2/templates/base.html

When the application is in debug mode, Include all javascript source rather than the prebuilt require.js file.
Uses the django.core.context_processors.debug context processor:
https://docs.djangoproject.com/en/1.7/ref/templates/api/#django-core-context-processors-debug

Javascript Debug Mode

---

.travis.yml
Makefile
requirements.txt
worth2/goals/tests/test_models.py
worth2/goals/tests/test_views.py
worth2/main/forms.py
worth2/main/tests/factories.py
worth2/main/tests/test_reports.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/selftalk/tests/test_views.py
worth2/templates/main/facilitator_sign_in_participant.html

I've fixed tests when using postgresql as test db, also, I'm now using
postgresql on travis, just like we're doing in PMT. This is because
there is some code that uses a postgresql-specific .distinct() method
that we need to be testing.
This commit also removes an unnecessary set_password() call in the
participant sign-in process.
Resolves PMT #100773

Participant sign-in fixes, preliminary work for PMT #100768, #100773

---

worth2/protectivebehaviors/utils.py
worth2/templates/pagetree/page.html
worth2/templates/pagetree/pagetree_submit_button.html

I fixed this by messing with some of the if statements in the templates. The logic is very fragile here -- if it was any more complicated than this, I think each `pagetree.Section` should handle its own template.

Fix validation on prot. behaviors quizzes - PMT #100763

---

worth2/templates/selftalk/statement_block.html

Marc may want to style this more, but this fixes the issue where
the feedback was bumping down the visual on the right.

Put form feedback closer to selftalk form - PMT #100726

---

requirements.txt
worth2/settings_production.py
worth2/settings_shared.py
worth2/settings_staging.py

This adds caching to worth as described here:
https://docs.djangoproject.com/en/1.8/topics/cache/
For local development, this will use the LocMemCache backend, which requires no
setup for developers:
https://docs.djangoproject.com/en/1.8/topics/cache/#local-memory-caching
Optionally, you can still override this in local_settings.py to use a local
memcached instance.
On staging and production, worth will connect to memcached. I've added
memcached to scuba and django in salt.

Add caching

---

worth2/settings_shared.py

This middleware causes problems with the site.
For example, if I add a pageblock to a section, the edit
page will reload with a cached version of the section edit
page that doesn't contain the pageblock.

Remove site-caching middleware

---

worth2/templates/goals/goal_check_in_block.html

This adds some text to the goal checkin activity if the participant hasn't completed the associated setting activity.

Add default empty view for goal checkin activity - PMT #100798

---

media/js/src/views/quiz-validator.js

The quizblock-validator previously mandated at least one answer was selected across a question type (single answer, multiple answer). As Worth quizzes generally are a single question, this approach worked fine.
The (new) Evaluation Quiz adds the complexity of a quiz with multiple questions of mixed type (single answer, multiple answer, short text, long text). In this case, the validator failed to correctly validate single answer & multiple answer questions.
For example, given 3 single answer questions, true was returned if just one question was answered.
This patch updates the quiz-validator to ensure at least one answer is checked for each question.

Quizblock Required Answer Enhancement

---

requirements.txt

Worth doesn't use google analytics, so we don't need this package.

Remove django-ga-context

---

requirements.txt

I don't think any dependencies are using this package -- if they were then pip
would complain because we're using `--no-deps`

Remove uuid dependency

---

worth2/main/models.py
worth2/main/tests/test_models.py
worth2/templates/main/participant_edit_row.html

Using instead the `Participant.highest_module_accessed` when
indicating participant progress.

Remove last_module_accessed method - PMT #100973

---

worth2/settings_shared.py

Jenkins isn't looking at the output from it, and it's very slow.
On my system, removing it reduces the time to run 'make' by 70 seconds

remove run_pylint step

---

worth2/main/apiviews.py
worth2/main/tests/test_apiviews.py

Seeing a lot of these: https://sentry.ccnmtl.columbia.edu/sentry-internal/worth2/group/659/
Probably from someone double-clicking submit or something.
At any rate, submitting multiple times ought to be harmless, rather than a 500 error.
Ideally, the response should be a 304 Not Modified, but I couldn't see
a straightforward way to get DRF to generate that.

Handle duplicate requests to /api/watched_videos/

---

worth2/goals/tests/test_views.py
worth2/templates/goals/goal_check_in_block.html
worth2/templates/goals/goal_setting_block.html

Because the goal setter renders its own submit button, it's
difficult to put the global success message in the same area as it.
It's possible of course, but for now I think it would just be more
trouble than it's worth, because it looks fine like this (see
attached screenshot).

Remove duplicate success message - PMT #101324

---

bdd_tests/features/intervention.feature
bdd_tests/features/participant_signin.feature
bdd_tests/steps/auth.py
bdd_tests/steps/common.py
worth2/main/tests/factories.py
worth2/templates/pagetree/page.html

One of the "Then" functions in the bdd steps didn't have an `assert`
on it, so it wasn't doing anything. This uncovered a bug with the
success alert on the goal setting page, and some problems with the
behave tests, which I've fixed.
I haven't gotten the create_pre_authenticated_session stuff to work,
even for normal, non-participant users, but doing the manual
sign-in is working for now.

Behave fixes

---

worth2/goals/migrations/0018_auto_20150702_1256.py
worth2/goals/models.py

This fixes this warning that started appearing in Django 1.8:
goals.GoalCheckInResponse.goal_setting_response: (fields.W342) Setting
unique=True on a ForeignKey has the same effect as using a
OneToOneField.
HINT: ForeignKey(unique=True) is usually better served by a
OneToOneField.

Make GoalCheckInResponse.goal_setting_response a OneToOneField

---

media/css/video.css

This causes the youtube iframe api to play high-res
videos instead of the low-res ones it defaults to, because
of the low `<video>` dimensions caused by the retina display.
This is related to, but doesn't fix, the low-quality thumbnails
(PMT #102083).

Play high-res video on retina display iPad

---

worth2/goals/forms.py
worth2/goals/mixins.py
worth2/goals/models.py
worth2/goals/tests/test_views.py

After this is pushed, each 'goal option' that has 'n/a' in the
text field needs to be updated to the new text here:
https://eworth.ccnmtl.columbia.edu/admin/goals/goaloption/

Change n/a goal option to something else - PMT #102176

---

worth2/main/migrations/0020_auto_20151016_0942.py
worth2/main/models.py
worth2/main/tests/test_apiviews.py
worth2/main/tests/test_models.py

This removes the validation from the study_id field while leaving in the
actual validator functions, because the earlier migrations depend on
them.

Remove validation from the participants' study id - PMT #103443

---

worth2/main/migrations/0021_auto_20151026_0929.py
worth2/main/models.py
worth2/main/tests/test_apiviews.py
worth2/main/tests/test_models.py

Turns out we do want validation.
This reverts commit 69fd071ca40dd895388af388259b72983053723c,
and adds a migration to re-add this validation.

Revert validation removal - PMT #103443

---

worth2/main/migrations/0022_auto_20151204_0916.py
worth2/main/models.py
worth2/main/tests/factories.py
worth2/main/tests/test_apiviews.py
worth2/main/tests/test_models.py
worth2/templates/main/participant_edit_row.html
worth2/templates/main/participant_id_instructions.html
worth2/templates/main/participant_list.html

This change is fine to be pushed whenever: the old participants (there
are 3 on production) will stay on the system, and we can update their
replacement IDs when we have them. I had told Jess we would need to
manually make a migration to handle this, and that we need the
replacement IDs in order to make this change, but it turns out that's
not the case.

Implement new study ID format - PMT #104086

---

worth2/main/models.py
worth2/templates/main/participant_id_instructions.html

Woops... the format is 13 digits not 12. Also, I've changed the
wording because the term "string" could mean any number of things
outside the context of programming.

Fix study id description

---

media/css/main.css

The spacing for these icons is a little off without this.

Add icon CSS on journal page

---

worth2/templates/main/facilitator_sign_in_participant.html

The participant sign in form had `action="""`, which is invalid
HTML. The action attribute isn't necessary for this form so I've
removed it.
I also moved the csrf_token up to the `<form>` tag. This makes it
obvious that this form has a CSRF token when grepping through the
code.

Remove invalid attribute on sign in form

---

worth2/templates/goals/goal_check_in_block.html

This is a quick fix for an urgent problem.
This shouldn't cause any problems.. and I want to err on the side of letting
participants through rather them locking them, preventing them from
completing the session.

explicitly unlock goal review session - PMT #104947

---

features/index.feature
worth2/templates/main/facilitator_dashboard.html

Regular facilitators are incorrectly using the demo view for participants. This wreaks havoc on research data collection. Lock this feature down to staff only.

Hide Demo View from Facilitators

---

worth2/main/generic/models.py
worth2/main/reports.py
worth2/main/tests/test_models.py
worth2/main/tests/test_reports.py

Factoring percent_complete variations into common profile methods to correct variations between the UI and reports. Due to the complexity of the goal review activity, page visits do not need to be "complete" in order to be counted.

percent_complete refactoring

---

worth2/templates/impersonate/list_users.html

to eliminate compress's complaint `impersonate/list_users.html: 'url' is not a valid tag or filter in tag library 'future'`

remove load from future tag from impersonate template

---

worth2/main/smoke.py

The `Avatar` model has an `is_default` field that says:
> If this is the initial avatar for all participants,
>	set this option to True. There can only be one default avatar
>  in the system.
There's a `clean()` method that enforces that if/when it's called, but
it could still be changed by other means, so this adds a smoketest to
make sure this constraint is not violated in production without an alert
being raised.

add smoketest to check avatar uniqueness

---

worth2/settings_shared.py

goals, protectivebehaviors, selftalk, and ssnm are not being included in jenkins coverage reporting

report test coverage and such on all apps

---

requirements.txt
worth2/settings_shared.py

The only thing that seemed to be holding it back to 1.8 was `typogrify`,
which doesn't appear to be used anywhere anyway.

:arrow_up: Django 1.9

---

worth2/goals/mixins.py

This problem arose from using a bare `except` clause. I was trying to
call `create_or_update()`, but the method is actually called
`update_or_create()`, so the execution was always failing into the
except clause. There's really no exceptions that I'm expecting here, so
I just removed the try/except.

Fix GoalCheckIn IntegrityError - PMT #109718

---

requirements.txt
worth2/settings_shared.py
worth2/templates/epub/container.xml
worth2/templates/epub/content.opf
worth2/templates/epub/ez-section.html
worth2/templates/epub/form.html
worth2/templates/epub/image.html
worth2/templates/epub/section.html
worth2/templates/epub/title-page.html
worth2/templates/epub/toc.html
worth2/templates/epub/toc.ncx
worth2/urls.py

That library is an experimental feature that started out in forest. I
pulled it out into its own module so we can use it here.
It builds a very basic epub book out of a pagetree site.
As you will probably see, it is very, very barebones at the moment, only
supporting a couple of basic blocks. We never really got very far on
that in Forest because we didn't actually having anything driving it.
Especially since WORTH is mostly video and interactive content, the epub
that it currently generates is laughably unusable, with 'Unrenderable
Block' for most of the content.
But, we have to start somewhere. With this in place, we can start
working block by block to figure out how it should be rendered in an
epub, or to replace it outright with something else.

add django-pagetree-epub

---

worth2/main/migrations/0019_auto_20150701_1544.py
worth2/main/migrations/0021_auto_20151026_0929.py
worth2/main/models.py

function does nothing. Looks like it was once used for doing some
validation on a migration, but has since been emptied out. No point in
keeping it around. Removed the references to it from
migrations. Obviously, if those migrations run, they won't do whatever
validation the function used to do, but that's been true ever since it
was turned into a no-op.

remove study_id_validator()

---

media/js/src/ssnm/adapters/application.js
media/js/src/ssnm/serializers/application.js
requirements.txt
worth2/settings_shared.py
worth2/ssnm/apiviews.py
worth2/ssnm/serializers.py
worth2/ssnm/tests/test_apiviews.py
worth2/templates/ssnm/ssnm_js.html

hoping @nikolas can confirm that the `rest_framework_ember` stuff is no longer necessary with newer versions of djangorestframework (it was breaking the tests on 3.3+)

:arrow_up: djangorestframework 3.6.2

---

features/environment.py
features/steps/auth.py
requirements.txt
worth2/main/auth.py
worth2/main/models.py
worth2/main/tests/mixins.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/templates/main/avatar_selector_block.html
worth2/urls.py

I have it working and tests passing.
However, it looks like the code has been re-using the `is_active` attribute on basic django User's to mark a user as a participant (that can't login directly) rather than a regular user. Unfortunately, with Django 1.10 plus, you can't do an `authenticate()` or anything with an inactive users, so that breaks all the tests that involve participants.
I got rid of that, making the participant users regular users. That makes everything work, but I guess the side-effect is that someone could potentially login directly as a participant user. I don't know the app well enough to know if that is a serious problem in practice or not...

Django 1.11

---

features/environment.py
features/steps/auth.py
requirements.txt
worth2/main/auth.py
worth2/main/models.py
worth2/main/tests/mixins.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/templates/main/avatar_selector_block.html
worth2/urls.py

Reverts ccnmtl/worth2#826
This branch breaks the admin from logging in the participant in the sign-in-participant form, because there's a call to `authenticate` which no longer works. I need to address this before updating to django 1.11.

Revert "Django 1.11"

---

media/css/main.css
worth2/main/templatetags/participanttags.py
worth2/main/tests/test_views.py
worth2/main/views.py
worth2/templates/main/dashboard.html
worth2/templates/main/journal_base.html
worth2/templates/main/journal_goal_responses.html
worth2/templates/main/journal_i_am_proud.html
worth2/templates/main/journal_i_am_worth_it.html
worth2/templates/main/journal_my_issue.html
worth2/templates/main/participant_edit_row.html
worth2/templates/main/session_1_journal.html
worth2/templates/main/session_2_journal.html
worth2/templates/main/session_3_journal.html
worth2/templates/main/session_4_journal.html
worth2/templates/main/session_5_journal.html
worth2/urls.py

Refactor the Participant Journal view into a logged-in user view. This PR also adds "empty" responses and links to the journal as needed.
Display print links & session progress on the dashboard:

Print Journal links

---

worth2/templates/goals/goal_check_in_block.html

The `goal_checkin_context` is a ZipFile rendering the check at Line 76 always True, even if there was no content. Resolving by using the `forloop.last` tag within the loop.

Goal Check-In: Hide submit button if goal setting skipped

---

media/js/src/ssnm/serializers/application.js

The ember-data adapter was serializing these fields as dash-case instead
of camelCase. 
```
provides-emotional-support: false
provides-practical-support: true
```
Apparently that change was in the JSON:API spec:
https://guides.emberjs.com/release/models/customizing-serializers/
But our backend doesn't support that... even though it is using
JSON:API. Anyways, customizing the serializer to snake_case its
attributes fixes this.

Fix Practical/Emotional support saving - EPFS-50

---

requirements.txt
worth2/settings_production.py
worth2/settings_staging.py

This library is better maintained than python-memcached.

Use pylibmc for memcached bindings

---

requirements.txt

Update to ctlsettings 0.3.0 which include changes for AWS migration.

INFRA-2634: Update ctlsettings to 0.3.0 for ALB Migration

---

requirements.txt

version 2.0.0 no longer exists.

Downgrade django-pageblocks to 1.3.0
