ccnmtl/worth2

- media/css/main.css
- worth2/main/auth.py
- worth2/main/models.py
- worth2/main/tests/mixins.py
- worth2/main/tests/test_views.py
- worth2/main/views.py
- worth2/templates/base.html
- worth2/templates/main/avatar_selector.html
- worth2/templates/main/break_modal.html
- worth2/urls.py
> Add avatar selection and "I need a break" modal

- requirements.txt
- worth2/settings_shared.py
- worth2/templates/admin/login.html
- worth2/templates/registration/login.html
- worth2/urls.py
Even though the final worth2 won't use CAS authentication, it's useful
for our staff to use CAS to log in to the in-progress worth2.
> Add back in CAS auth - PMT #98803

- .jscsrc
- Makefile
- media/js/src/main.js
- media/js/src/ssnm/components/modal-dialog.js
- media/js/src/ssnm/controllers/edit-supporter.js
- media/js/src/ssnm/controllers/supporters.js
- media/js/src/ssnm/helpers/radio-button.js
- media/js/src/ssnm/models/supporter.js
- media/js/src/ssnm/routes/application.js
- media/js/src/ssnm/views/radio-button.js
- media/js/src/views/edit-participant.js
- package.json
- worth2/ssnm/apiviews.py
- worth2/ssnm/serializers.py
- worth2/ssnm/tests/test_apiviews.py
- worth2/templates/ssnm/ssnm.html
Participants can now add supporters by using the series of modals after
clicking the "Add People" button.
This commit also adds jshint/jscs validation.
> SSNM supporter adding feature

- requirements.txt
- worth2/main/views.py
- worth2/templates/base.html
- worth2/templates/registration/login.html
- worth2/urls.py
Some preliminary steps for setting up the self-talk activity with quizblock. The main change here is just adding the content-nav block to `base.html`.
> Self talk setup - PMT #98029

- media/js/src/main.js
- media/js/src/views/create-participant.js
> Fix bug where study ID validation wasn't being displayed

- worth2/templates/main/avatar_selector.html
> Allow avatars to go on same line

- worth2/main/migrations/0007_auto_20150209_1030.py
- worth2/main/models.py
> Make quiz_class required to prevent user error

- worth2/main/tests/test_views.py
- worth2/templates/main/index.html
- worth2/urls.py
It's confusing, and besides it was causing style problems.
> Don't handle authentication in the index template

- worth2/main/forms.py
- worth2/main/migrations/0010_session_session_type.py
- worth2/main/models.py
- worth2/main/tests/test_views.py
- worth2/main/views.py
- worth2/templates/main/facilitator_sign_in_participant.html
This adds a required 'session type' param to the participant sign-in form.
I also read through the Django forms API and found some ways to simplify the participant sign-in form.
> Require a session type on participant sign-in - PMT #99224

- worth2/main/auth.py
- worth2/settings_shared.py
- worth2/ssnm/apiviews.py
- worth2/ssnm/auth.py
A Facilitator is considered any registered user in the system that's
"active". Participants are "inactive".
> Give facilitators access to editing participants - PMT #99221

- media/css/main.css
- media/js/src/views/create-participant.js
- media/js/src/views/edit-participant.js
- worth2/main/models.py
- worth2/main/serializers.py
- worth2/main/tests/test_apiviews.py
- worth2/main/views.py
- worth2/templates/main/participant_edit_row.html
- worth2/templates/main/participant_list.html
Add new participant field with validation and tests
> Add Cohort ID to participant manager - PMT #99223

- media/css/main.css
- worth2/templates/base.html
Also changing all references from `request.user` to `user` in the base template.
> Add participant avatar to nav header - PMT #98026

- requirements.txt
New django storages is here:
https://github.com/jschneier/django-storages
> Update django-storages in attempt to fix s3 assets not updating

- .gitignore
- worth2/goals/migrations/0006_auto_20150215_0934.py
- worth2/goals/migrations/0007_auto_20150215_1428.py
- worth2/goals/migrations/0008_auto_20150216_1057.py
- worth2/goals/models.py
- worth2/goals/tests/factories.py
- worth2/goals/tests/test_views.py
- worth2/main/generic/models.py
- worth2/main/models.py
- worth2/main/views.py
- worth2/settings_shared.py
- worth2/ssnm/models.py
- worth2/templates/goals/goal_check_in_block.html
- worth2/templates/goals/goal_review_block.html
- worth2/templates/goals/goal_setting_block.html
I added some more functionality to the goal setting activity (PMT #98022)
so Jess will be able to review it. The form now populates with existing
responses and displays the correct labels for the forms (main or extra).
Also laid out some initial steps for the goal review and check-in activities
(PMT #98023).
> Goal setting polishing + initial goal review / check-in setup.

- requirements.txt
- worth2/s3utils.py
Same as commit here:
https://github.com/ccnmtl/pump/commit/7dd8fcfb696548f7afd0f257e7efbef1e1a3db1a
> Normalize timezone to UTC for S3 - PMT #99511

- media/css/main.css
- media/js/src/app.js
- media/js/src/views/goal-setting-form.js
- worth2/goals/admin.py
- worth2/goals/forms.py
- worth2/goals/migrations/0012_goalsettingresponse_other_text.py
- worth2/goals/mixins.py
- worth2/goals/models.py
- worth2/goals/tests/test_views.py
- worth2/main/admin.py
- worth2/main/views.py
- worth2/templates/goals/goal_setting_block.html
Add the 'Other' field to goal setter, that's only required if the 'Other' option is selected from the dropdown.
> Add Goal Setting "Other" option - PMT #98022

- media/css/main.css
- media/js/src/app.js
- media/js/src/views/goal-checkin-form.js
- worth2/goals/admin.py
- worth2/goals/forms.py
- worth2/goals/migrations/0013_auto_20150220_1139.py
- worth2/goals/migrations/0014_auto_20150220_1446.py
- worth2/goals/mixins.py
- worth2/goals/models.py
- worth2/goals/tests/test_views.py
- worth2/main/views.py
- worth2/templates/goals/goal_check_in_block.html
This adds conditional validation to the goal check-in form, and some
JavaScript to display the form fields only when they are required.
This also includes a fix to the goal setter - PMT #99641
> Add Goal check-in form interactive functionality - PMT #98023

- worth2/main/views.py
Jess has requested that gating be turned off while we're still in
the stages of entering content.
Maybe in the future we can make this configurable within pagetree so
it doesn't require a code change.
> Turn off gating - PMT #99625

- .project
- .pydevproject
- media/css/main.css
- worth2/templates/quizblock/likert.html
- worth2/templates/quizblock/question.html
- worth2/templates/quizblock/single_choice.html
* Refactored out the rate-my-risk.html template	into a generic quizblock/likert.html template.
* Modified the likert scale to show a disabled/selected state after submission.
* Post Video quizzes require extra css styles "post-video-quiz likert"
* Rate My Risk quiz will require extra css style "likert". (Unclear from spec what the submission state is for this type of quiz)
> Post video quiz / Rate My Risk

- media/css/ssnm.css
Fixes rendering on mobile safari
> Add -webkit-flex rules on SSNM ipad style

- media/css/main.css
- worth2/main/templatetags/quizresults.py
- worth2/templates/pagetree/page.html
- worth2/templates/quizblock/single_choice.html
- worth2/templates/quizblock/single_choice_show_answer.html
Submit / Clear buttons - making a little space until real styling happens
Multiple Choice, Single Answer, Submit State - disable inputs rather than remove them
Template tag to get question correct/incorrect based on user response.
Display correct/incorrect feedback for a question. Distinct divs to allow styling.
> Myth/Fact Quiz Construction

- media/css/main.css
- worth2/templates/pagetree/page.html
- worth2/templates/quizblock/single_choice.html
> Add some protective behavior styling - PMT #98028

- media/css/main.css
I need to give the rate my risk quiz the rate-my-risk class
instead of protective-behaviors, so the submission doesn't
show up in the "stuff i do" results.
> Small css fix for protective-behaviors activity

- .travis.yml
https://github.com/ccnmtl/worth2/pull/78#commitcomment-9911138
http://docs.travis-ci.com/user/caching/#Arbitrary-directories
> Add 'cache: pip' on travis in attempt to speed up builds

- worth2/goals/mixins.py
- worth2/goals/tests/test_views.py
- worth2/templates/goals/goal_check_in_block.html
* Display correct goal response type on checkin page
* Hide n/a option on checkin page
> Goal checkin bugfixes - PMT #99666

- media/css/main.css
- worth2/main/generic/models.py
- worth2/main/models.py
- worth2/main/tests/test_models.py
- worth2/settings_shared.py
- worth2/templates/main/avatar_selector_block.html
- worth2/templates/main/facilitator_dashboard.html
- worth2/templates/main/facilitator_sign_in_participant.html
- worth2/templates/main/participant_edit_row.html
- worth2/templates/main/participant_list.html
- worth2/templates/main/participant_progress_row.html
* Added a progress viewer
* Removed lorem ipsum text
> Dashboard updates - PMT #99664

- worth2/templates/admin/login.html
See https://github.com/ccnmtl/ccnmtldjango/pull/48
> Fix styles on our custom admin login override

- media/js/src/app.js
- media/js/src/views/sign-out-participant.js
- media/js/src/views/unlocker.js
- package.json
- worth2/main/apiviews.py
- worth2/main/tests/test_apiviews.py
- worth2/templates/main/break_modal.html
- worth2/urls.py
> Add participant signout feature - PMT #99769

- media/css/main.css
- worth2/templates/pagetree/page.html
- worth2/templates/quizblock/long_text.html
- worth2/templates/quizblock/question.html
* also, changing "clear my answers and try again", to "change my answers" as that seems more correct for this application. will confirm with Jess.
> Safety Plan long text questions

- worth2/main/generic/models.py
- worth2/main/models.py
- worth2/selftalk/admin.py
- worth2/selftalk/migrations/0001_initial.py
- worth2/selftalk/models.py
- worth2/selftalk/tests/factories.py
- worth2/selftalk/tests/test_models.py
- worth2/settings_shared.py
This adds all the models and factories I'll be using for the Self-Talk
activity.
> Self Talk initial steps - PMT #98029

- media/css/main.css
- worth2/templates/protectivebehaviors/protective_behaviors_results.html
- worth2/templates/quizblock/multiple_choice.html
- worth2/templates/quizblock/multiple_choice_show_answer.html
- worth2/templates/quizblock/question.html
- worth2/templates/quizblock/single_choice.html
- worth2/templates/quizblock/single_choice_show_answer.html
plus, refactoring/styling based on consultation with Marc. We've agreed to a base col-md-8, col-md-4 quiz layout, with the avatar and any other elements always living in col-md-4 if required.
> Practicing Negotiation Quiz

- worth2/goals/mixins.py
- worth2/goals/models.py
- worth2/goals/tests/test_views.py
- worth2/main/generic/models.py
- worth2/main/views.py
- worth2/selftalk/migrations/0002_auto_20150304_1512.py
- worth2/selftalk/mixins.py
- worth2/selftalk/models.py
- worth2/selftalk/tests/test_models.py
- worth2/selftalk/tests/test_views.py
- worth2/templates/selftalk/refutation_block.html
- worth2/templates/selftalk/statement_block.html
The next step is to implement the refutation block's form.
> Add negative statement form functionality - PMT #98029

- requirements.txt
import/export fixes.
see: https://github.com/ccnmtl/django-quizblock/pull/38
and: https://github.com/ccnmtl/django-pagetree/pull/53
> Integrate new PageTree/QuizBlock changes

- media/css/ssnm.css
- media/js/src/ssnm/helpers/influence-color-class.js
- media/js/src/ssnm/models/supporter.js
- worth2/templates/ssnm/ssnm_js.html
- worth2/templates/ssnm/ssnm_page_block.html
> Add glyphicons and colors to SSNM boxes. PMT #99856

- media/js/src/views/self-talk-road.js
- worth2/templates/selftalk/self_talk_road.html
This isn't complete, I think I'll need some 3d rendering library
to correctly calculate the co-ordinates for the avatar on the road.
I just want to get this onto master so I can show Jess tomorrow
how it's responding to the form's checkboxes.
> Generalize self-talk road rendering and respond to form events

- media/js/src/views/self-talk-road.js
- worth2/templates/base.html
Fixes the activity on production.
> Use STATIC_URL in javascript for selftalk asset

- media/css/main.css
- media/js/src/app.js
- media/js/src/views/quiz-validator.js
- worth2/templates/pagetree/page.html
This is the first step for js quiz validation. It only looks at radio buttons so far. My next step is to come up with some scheme of marking each question as required/not required, possibly just using the existing `css_extra` attribute.
> Add JS quiz validation for radio button forms - PMT #99862

- worth2/main/models.py
- worth2/main/tests/factories.py
- worth2/main/tests/test_apiviews.py
We now have the spec, so we can actually validate the participant ID.
> Add actual participant id validation - PMT #99972

- media/js/src/main.js
- media/js/src/views/create-participant.js
- media/js/src/views/edit-participant.js
- media/js/src/views/self-talk-road.js
- media/js/src/views/sign-in-participant-filter.js
- media/js/src/views/sign-out-participant.js
- worth2/selftalk/mixins.py
- worth2/selftalk/models.py
- worth2/templates/selftalk/refutation_block.html
- worth2/templates/selftalk/statement_block.html
Also: add blank default option to refutation forms.
> Connect selftalk road to refutation dropdown form

- worth2/main/admin.py
- worth2/main/migrations/0014_auto_20150313_1206.py
- worth2/main/migrations/0015_avatar_is_default.py
- worth2/main/models.py
- worth2/main/templatetags/avatar.py
- worth2/main/tests/test_views.py
- worth2/templates/main/avatar_selector_block.html
This also includes the missing migration from
https://github.com/ccnmtl/worth2/pull/129 so the migrations don't
get out of sync.
> Add default avatar functionality for participants - PMT #99711

- worth2/goals/models.py
- worth2/goals/tests/factories.py
- worth2/goals/tests/test_models.py
Fixes this sentry error:
https://sentry.ccnmtl.columbia.edu/worth-2/worth2/group/584/
> Fix unicode error when displaying GoalSettingResponse - PMT #100229

- worth2/goals/mixins.py
- worth2/goals/tests/test_views.py
- worth2/templates/goals/goal_check_in_block.html
* "Other" text wasn't showing up on settings page
* Goal responses were out of order on checkin page
* goal_amount was off by one.
* Some template fixes
> Fix some goal setting/checkin bugs

- worth2/templates/goals/goal_setting_block.html
Added a missing clearfix element
> Goal setting style fix

- worth2/main/migrations/0017_simpleimageblock.py
- worth2/main/models.py
- worth2/settings_shared.py
- worth2/templates/main/simpleimageblock.html
PMT #100464
from meaningfulconsent:
https://github.com/ccnmtl/django-pageblocks/issues/5#issuecomment-86676627
> add SimpleImageBlock

- media/js/src/forms/selftalk-refutationform.js
- worth2/main/views.py
- worth2/selftalk/migrations/0003_auto_20150330_1229.py
- worth2/selftalk/migrations/0004_refutationresponse_statement.py
- worth2/selftalk/mixins.py
- worth2/selftalk/models.py
- worth2/selftalk/tests/factories.py
- worth2/selftalk/tests/test_views.py
* Fix 'clear answers' button on custom forms
* populate initial data correctly on refutation form
* Fix 'other' functionality on selftalk refutation form
> Associate selftalk refutations with correct responses

- worth2/selftalk/forms.py
Need to reference these URLs correctly for s3.
> use STATIC_URL in selftalk form media

- media/css/main.css
- worth2/main/tests/test_utils.py
- worth2/main/tests/test_views.py
- worth2/main/utils.py
- worth2/main/views.py
- worth2/settings_shared.py
- worth2/templates/main/participant_journal.html
> Restructure participant journals, and add some dynamic data

- worth2/main/forms.py
- worth2/main/migrations/0018_auto_20150410_1355.py
- worth2/main/models.py
- worth2/main/tests/factories.py
- worth2/main/tests/test_models.py
- worth2/main/tests/test_views.py
- worth2/main/views.py
I'm getting rid of the poorly-named Session model, replacing it
with Encounter, and adding in some functionality.
> Session/Encounter updates - PMT #100688

- worth2/main/forms.py
- worth2/main/tests/test_views.py
- worth2/main/views.py
This dropdown is connected to JS code that relies on the 'name'
to be 'participant_id'.
> Fix bug that was causing participant dropdown to be empty.

- worth2/main/tests/test_views.py
- worth2/main/views.py
- worth2/templates/main/journal_ssnm_display.html
- worth2/templates/main/journal_ssnm_supporter_display.html
- worth2/templates/main/session_1_journal.html
- worth2/templates/main/session_2_journal.html
- worth2/templates/main/session_3_journal.html
- worth2/templates/main/session_4_journal.html
- worth2/templates/main/session_5_journal.html
Also includes a refactor to the journal view. All the HTML is now
in the templates where it should be.
> Add SSNM viewer to Participant Journal - PMT #98030

- worth2/goals/mixins.py
- worth2/goals/tests/test_views.py
When a goal is updated by the participant, clear any check-in
responses associated with it.
> Fix goal setting revision bug - PMT #100717

- requirements.txt
- worth2/settings_shared.py
See https://github.com/ccnmtl/dmt/pull/395
> Use django DiscoverRunner instead of nose.

- worth2/main/tests/test_reports.py
fully covering report model & view
> Report Test Coverage

- worth2/main/forms.py
- worth2/templates/main/facilitator_sign_in_participant.html
> Move "Next, new session" option to top, and make it default

- worth2/main/tests/test_reports.py
- worth2/main/views.py
- worth2/templates/main/facilitator_dashboard.html
https://pmt.ccnmtl.columbia.edu/item/100799/
> Staff-only report access.

- worth2/selftalk/forms.py
- worth2/selftalk/mixins.py
- worth2/settings_shared.py
- worth2/templates/selftalk/statement_block.html
> Add validation to selftalk statement form - PMT #100764

- worth2/main/tests/factories.py
- worth2/main/tests/test_reports.py
- worth2/main/tests/test_views.py
Referencing PMT #100768. This bug seems already fixed, and these
tests help ensure that.
> Add more thorough testing for the sign-in form

- worth2/templates/base.html
UNI logout was redirecting improperly to the admin logout screen
> Fix UNI logout

- media/css/main.css
- worth2/main/views.py
- worth2/templates/main/journal_base.html
- worth2/templates/main/session_1_journal.html
- worth2/templates/main/session_2_journal.html
- worth2/templates/main/session_3_journal.html
- worth2/templates/main/session_4_journal.html
- worth2/templates/main/session_5_journal.html
Further finalizing a lot of the static content on the journals.
The rest of the Dynamic content will come after all the basic
structure is down.
> Journal revisions - PMT #98030

- bdd_tests/features/index.feature
- bdd_tests/features/intervention.feature
- bdd_tests/steps/auth.py
- bdd_tests/steps/common.py
- worth2/main/tests/factories.py
- Added a method for quickly creating an authenticated session.
> Add behave test for basic participant navigation - PMT #100729

- media/css/main.css
- worth2/templates/quizblock/single_choice.html
* includes generic likert question styling
> Evaluation Quiz styling

- media/css/main.css
- worth2/main/tests/test_views.py
- worth2/main/utils.py
- worth2/main/views.py
- worth2/templates/main/journal_goal_responses.html
- worth2/templates/main/journal_i_am_worth_it.html
- worth2/templates/main/session_1_journal.html
- worth2/templates/main/session_2_journal.html
- worth2/templates/main/session_3_journal.html
- worth2/templates/main/session_4_journal.html
- worth2/templates/main/session_5_journal.html
Adds these dynamic blocks to the journals: 
"Reflections" block to journal 2:
Goals responses:
> Add "I am WORTH it" quiz responses to journals - PMT #98030

- worth2/goals/models.py
- worth2/goals/tests/test_models.py
- worth2/main/tests/test_views.py
- worth2/main/utils.py
- worth2/main/views.py
- worth2/templates/main/journal_i_am_worth_it.html
- worth2/templates/main/session_4_journal.html
* Added safety plan content
* Moved response query methods out of the view
* Added dynamic data for "I am WORTH it" responses to journals
> Journal updates - PMT #98030

- requirements.txt
Fixes sentry error:
https://sentry.ccnmtl.columbia.edu/sentry-internal/worth2/group/699/
> Update django-ordered-model to fix 500 error

- media/css/main.css
- worth2/templates/goals/goal_setting_block.html
- worth2/templates/pagetree/page.html
- worth2/templates/pagetree/pagetree_submit_button.html
Float the alert-success, alert-dangers to the right of the submit button
> Quizzes: success/error message placement

- media/css/main.css
- worth2/main/utils.py
- worth2/main/views.py
- worth2/templates/main/journal_base.html
- worth2/templates/main/session_4_journal.html
Fixes a bug in get_quiz_responses_by_css_in_module where
it wasn't querying responses from all necessary quizblocks.
> Add dynamic data to journal 4 safety plan - PMT #98030

- requirements.txt
Picking up this change: https://github.com/ccnmtl/django-pagetree/pull/87
> upgrade to django_pagetree 1.1.4

- media/css/main.css
* Answer level feedback. (with the default white box styling)
* Answer is required
* No redo
* No avatar
* css class: negative-self-talk
> Negative Self Talk Quiz Styling

- media/css/main.css
- media/css/video.css
- requirements.txt
- worth2/templates/goals/goal_check_in_block.html
- worth2/templates/goals/goal_setting_block.html
- worth2/templates/main/facilitator_sign_in_participant.html
Also, I cleaned up goal form rendering
> Fix sign-in page styling, and myth/fact video duration

- media/css/main.css
- worth2/templates/goals/goal_check_in_block.html
- worth2/templates/goals/goal_setting_block.html
- worth2/templates/pagetree/page.html
- worth2/templates/selftalk/statement_block.html
* Goal setting check in, move the success button down next to the submit button
* Goal setting - remove the large bottom margin after the submit button
* "lead" style for Self talk intros.
> Style tweaks

- media/js/src/views/edit-participant.js
- worth2/main/tests/test_views.py
- worth2/main/views.py
- worth2/templates/main/participant_confirm_delete.html
- worth2/templates/main/participant_edit_row.html
- worth2/urls.py
> Add confirmation page for participant archive - PMT #101073

- media/css/main.css
- worth2/templates/main/break_modal.html
- worth2/templates/pagetree/page.html
- worth2/templates/pagetree/pagetree_submit_button.html
- worth2/templates/selftalk/refutation_block.html
- worth2/templates/selftalk/statement_block.html
* moving from top of template to next to the submit button
* also...tweaking some safety plan styles
> Move Self-talk messaging

- worth2/selftalk/mixins.py
- worth2/selftalk/tests/test_views.py
- worth2/selftalk/utils.py
- Fixed a bug where the form fields weren't getting populated
with submitted responses.
- Disable the form fields when the form is in the 'submitted' state
> Self-Talk form changes - PMT #101151

- worth2/main/generic/models.py
- worth2/main/models.py
- worth2/main/tests/test_models.py
- worth2/main/tests/test_utils.py
- worth2/main/utils.py
I've removed a bunch of unnecessary methods since cleaning up
the participant sign-in form.
> Remove unused methods

- .travis.yml
- bdd_tests/environment.py
- bdd_tests/features/intervention.feature
- bdd_tests/features/participant_signin.feature
- bdd_tests/steps/auth.py
- bdd_tests/steps/avatars.py
- bdd_tests/steps/common.py
- bdd_tests/steps/quiz.py
- requirements.txt
- worth2/main/tests/factories.py
This adds some integration testing to the avatar activity and
one of the quizzes. I'm also building out a mock instance of the
worth application as "WorthModuleFactory" that's used both in
the behave tests and the unit tests.
For now, in behave, I still have to go through the participant
sign-in process manually. I couldn't get the
create_pre_authenticated_session scheme to work for signing in
participants. There's comments on this in the code.
> Integration testing for the intervention - PMT #100729

- media/js/src/views/youtube-player.js
> Turn off YouTube controls

- worth2/goals/forms.py
- worth2/selftalk/mixins.py
- worth2/templates/goals/goal_setting_block.html
The self-talk refutation other field now reads:
"Type how you would turn this around"
The goal setting other field now reads:
"Please type your response here"
The goal review other field now reads:
"Please type your response here"
> Update placeholder text for "Other" form fields - PMT #101333

- worth2/main/migrations/0019_auto_20150701_1544.py
Editing the validation message here caused a migration update.
> Add missing Participant.study_id migration

- features/intervention.feature
- features/steps/common.py
- worth2/goals/models.py
- worth2/main/tests/factories.py
This includes a time.sleep(1) call in one of the steps to try
and avoid the intermittent behave failure we saw on travis earlier
today.
> Basic behave testing for sessions 4/5 - PMT #100729

- worth2/templates/main/session_4_journal.html
The first paragraph here was old and didn't correspond
with what's here:
http://wiki.ccnmtl.columbia.edu/index.php/Journal_spec_worth_2
> Update session 4 journal

- media/css/main.css
- worth2/templates/base.html
- worth2/templates/main/journal_my_issue.html
- worth2/templates/pagetree/page.html
> Render services icons on journal page - PMT #102348

- .travis.yml
- features/steps/common.py
This is an attempt to address a flakey behave test.
> Use selenium's implicit wait - PMT #102226

- .jshintrc
- media/js/src/ssnm/adapters/application.js
- media/js/src/views/sign-out-participant.js
`.jshintrc` to enforce eqeqeq checking.
> jshint eqeqeq

- .travis.yml
- features/environment.py
- features/index.feature
- features/steps/auth.py
- features/steps/avatars.py
- features/steps/common.py
- features/steps/goals.py
- features/steps/quiz.py
- requirements.txt
- worth2/templates/base.html
- worth2/templates/main/break_modal.html
- worth2/templates/main/participant_edit_row.html
- worth2/templates/registration/login.html
Selenium 2.48.0 is required for FF 43+, which is the version of Firefox
I have on my computer.
I'm experimenting with trying to fix the unreliable "Manage Participant
IDs" step in behave. I've moved some things around, added a fix for
link clicking. I'm calling selenium methods directly now instead of going
through splinter. This is to eliminate a potentially problematic layer of
abstraction.
> :arrow_up: selenium 2.48.0 + remove splinter

- worth2/main/reports.py
- worth2/main/tests/test_reports.py
* Report time as 24-hour rather than 12-hour
* Fix double increment of module_idx
* Add 15 columns to hold the dates - 3 for each encounter. (initial, 1st makeup, 2nd makeup). Format YYMMDD.
> Raw Data Report Adjustments

- worth2/selftalk/models.py
let's not overcomplicate a plain if/else...
> simplify a conditional

- worth2/settings_shared.py
- worth2/urls.py
some changes to push worth towards being 1.10 compatible.
Currently, the version of DRF in use is not 1.10 compatible (or at least, how it's used in the project isn't), so it can't be upgraded without some effort.
But in the meantime, a few things can be cleaned up independently.
> Django 1.10 prep

- requirements.txt
djangorestframework expects it and is complaining during the compress
phase.
> add django-crispy-forms

- worth2/main/tests/test_utils.py
- worth2/main/tests/test_views.py
- worth2/main/utils.py
- worth2/main/views.py
- worth2/templates/main/dashboard.html
- worth2/urls.py
Beginning to migrate this from a facilitated experience to an open, self-paced resource. First step, create a dashboard for everyone. I'm choosing to leave all the Participant code in place for the moment. That will all get cleaned out a bit later. And, the design is rudimentary at this stage as well.
> Transitioning facilitator dashboard to general dashboard

- media/css/main.css
- worth2/templates/base.html
- worth2/templates/main/dashboard.html
- worth2/templates/pagetree/page.html
- worth2/templates/registration/login.html
Primarily for login page and landing page -- color contrast, alt tags, content layout, etc.
> Accessibility first steps

- worth2/templates/main/dashboard.html
- worth2/templates/pagetree/page.html
> Screenreader support

- media/css/main.css
- media/js/src/views/quiz-validator.js
- worth2/templates/goals/goal_check_in_block.html
- worth2/templates/goals/goal_setting_block.html
- worth2/templates/pagetree/page.html
- worth2/templates/pagetree/pagetree_submit_button.html
* goal check-in & protective behaviors remain ungated.
> Add back clientside gating for quizzes

- worth2/templates/quizblock/single_choice.html
The 80% view for most of the quizzes just didn't fit here.
> Stretch likert across the page

- media/js/src/views/quiz-validator.js
- worth2/templates/pagetree/pagetree_submit_button.html
* Prompt the user to click submit if they haven't
* Don't gate goal setting & checkin
> Quiz gating refinement

- media/css/main.css
- media/css/selftalk.css
Primarily, this was an effort to make the font sizes and weights consistent across the application. A few more tweaks as well.
> Polish the styles
